# GoReleaser configuration
version: 2

# Build configuration
builds:
  - id: gURL
    main: ./main.go
    binary: gURL
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Ignore specific combinations if needed
    ignore:
      - goos: windows
        goarch: arm64

# Archive configuration
archives:
  - id: gURL
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - AUTHENTICATION.md

# Release configuration
release:
  disable: false

# Changelog configuration
changelog:
  disable: true

# Checksum configuration
checksum:
  name_template: "checksums.txt"
